<h2>One-Hour Guild Presentation</h2>
<h3>Friends and Family:  The Lancaster Diamond Sampler Quilt<br></h3>
<img src="http://wdsolutionsonline.com/ahquilting/cust-img/LDOriginalQuilt_small.jpg" style="border:0px #000000;width:150px;height:154px;float:right;margin-left:20px" title="Lancaster Diamond Sampler Quilt" alt="Lancaster Diamond Sampler Quilt"><p>This quilt is one of a small group of similar quilts that were made in Lancaster County, Pennsylvania, in the mid-1800s by a group of quilters who referred to themselves as the "girl cousins."&nbsp;They were friends and family, old and young, new quilters and experienced quilters, who got together to visit, to eat, to share knowledge, fabric, and patterns, and to work on quilts.  Ann fell in love with this quilt and has been studying it and making the blocks since 2009 - she just keeps discovering more interesting and mysterious features every day about the quilt and the unknown quilter who created it.  This fun and informative lecture and trunk show lasts about one hour.  Ann will discuss the various techniques used in these quilts, learn some surprisingly easy geometry, and even take the Mystery Appliqué&nbsp;Quiz.  This quilt will remind you why you got into quilting in the first place.</p>
<h2><br></h2><h2>Six-Hour Workshops</h2> 
<h3>Orphan
Blocks and Backward Scrapping</h3> 
<img src="http://www.wdsolutionsonline.com/ahquilting/cust-img/OrphanLD_small.jpg" style="border:0px #000000;width:126px;height:195px;float:right;margin-left:20px" title="Orphan Blocks Lancaster Diamond Quilt" alt="Orphan Blocks Lancaster Diamond Quilt"><p>Somewhere&nbsp;in your sewing area, in a box or a drawer or a tub or a shopping bag, are your&nbsp;forgotten blocks and unfinished tops. Here is your chance to rescue and recycle them into a scrap quilt that will be loved and actually used.&nbsp; You
will use Ann's Lancaster Diamond Template along with your rotary cutter and mat to cut your orphan blocks and tops into these diamond shapes.&nbsp; Ann refers to this technique as "Backwards Scrapping"&nbsp;because you are cutting up assembled  locks/tops into a new arrangement.  <br></p>
<p>Supply lists and project sheets will be provided for making different size quilts with
different border options: table runner, wall-hanging, crib, twin, queen sizes.&nbsp; You may also choose to make this quilt from fat quarters or other yardage.  <br></p>
<p>This workshop is a good full-day class for an experienced quilter or for a confident beginner who has rotary cutting skills.<br></p>
<h3>Getting Started with the Lancaster Diamond Sampler</h3>
<img src="http://wdsolutionsonline.com/ahquilting/cust-img/Pinwheel_thumb.jpg" style="border:0px  #000000;width:107px;height:160px;margin-left:20px;margin-bottom:20px;float:right" title="Fun Diamond Quilt" alt="Fun Diamond Quilt">
<p>If you have your template and your copy of the book, “Making the Lancaster Diamond Sampler: A 19th Century Quilt Design by Fanny’s Friend,” you are ready to begin making blocks.  Ann will select blocks to help you get started working on your own or with a group.  There are several design and construction techniques that you can implement early on in the process that will make the journey with this quilt fun and rewarding.   A supply list will be provided to help you get started with fabric selections for blocks, sashing, and cornerstones.<br></p>
<h2><br></h2><h2>Two-Day Retreat</h2> 
<h3>Making the Lancaster Diamond Sampler</h3>
<img src="http://www.wdsolutionsonline.com/ahquilting/cust-img/ElementsCloseup_small.jpg" style="width:150px;height:142px;margin-left:20px;float:right" title="Lancaster Diamond Sampler" alt="Lancaster Diamond Sampler"><p>The blocks in the original sampler quilts were made in an informal teaching environment in the mid-1800s.&nbsp; Quilters
shared patterns, fabric, and knowledge with each other in order to pass along the traditions of quilting.&nbsp; They also
ate, gossiped, laughed, and generally had fun.&nbsp; In this spirit, you will make blocks from the different styles and
techniques found in this fascinating quilt:&nbsp; strip piecing, basic elements, appliqué  , Seminole.&nbsp; Ann will teach you to use both modern and 1800s techniques for making these blocks.&nbsp; The grand finale, will have you making miniature diamond blocks that feature ¼"&nbsp;checkerboards (don't be frightened, it's easier than you think!).&nbsp;</p>